package org.digidoc4j;

public class Certificates {
  public final static String TS_CERTIFICATE = "MIIGOzCCBSOgAwIBAgIUe6m/OP/GwmsrkHR8Mz8LJoNedfgwDQYJKoZIhvcNAQELBQAw" +
      "fzELMAkGA1UEBhMCQk0xGTAXBgNVBAoTEFF1b1ZhZGlzIExpbWl0ZWQxJTAjBgNVBAsTHFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkx" +
      "LjAsBgNVBAMTJVF1b1ZhZGlzIFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTIwMjIwMTYyNTAwWhcNMjEwMzE3MTgzMzMzWjCB" +
      "uTELMAkGA1UEBhMCQ0gxGTAXBgNVBAoTEFF1b1ZhZGlzIExpbWl0ZWQxHTAbBgNVBAsTFFRpbWUtc3RhbXAgQXV0aG9yaXR5MScwJQYDVQQL" +
      "Ex5uQ2lwaGVyIERTRSBFU046RkJDOS0zMDU2LUNFMEExJDAiBgNVBAsTGzEuMy42LjEuNC4xLjgwMjQuMC4yMDAwLjYuMDEhMB8GA1UEAxMY" +
      "dHNhMDEucXVvdmFkaXNnbG9iYWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxRhvUNoyEkX0cSQoOPpmnue7iF2o4mkd" +
      "ccfqJl5gZRkbIPoEUB5y70tnzBCBaCs8kxkkREPQoIOlL5bG+qj/j2hR6j2ZTmMAagplQ3hCRxkUj2wv1z8Va3k3fxLihh4zElJHYw9LXmwW" +
      "p0djSG3JxoVtu7tYlktoKsVVG1mznxs8ZA8D+uIPYxbUsME2k9lC1xiTGTtdfLBOdS5+NQmZw4HxaF+dycMcA94BhACv1me1T0yvC6Gfzpon" +
      "Bk7cg4WWBLk6BL4khofv0mujTvWJ5axzE+eGcHem+PbGS8b/fCv22l7kAKvmeiMhdnyvzFMGHPj747mI0U29VBqHawJYsQIDAQABo4ICcjCC" +
      "Am4wOgYIKwYBBQUHAQEELjAsMCoGCCsGAQUFBzABhh5odHRwOi8vb2NzcC5xdW92YWRpc2dsb2JhbC5jb20wggEiBgNVHSAEggEZMIIBFTCC" +
      "AREGCysGAQQBvlgAj1AGMIIBADCBxwYIKwYBBQUHAgIwgboagbdSZWxpYW5jZSBvbiB0aGUgUXVvVmFkaXMgUm9vdCBDZXJ0aWZpY2F0ZSBi" +
      "eSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlv" +
      "bnMgb2YgdXNlLCBhbmQgdGhlIFF1b1ZhZGlzIENlcnRpZmljYXRlIFByYWN0aWNlIFN0YXRlbWVudC4wNAYIKwYBBQUHAgEWKGh0dHA6Ly93" +
      "d3cucXVvdmFkaXNnbG9iYWwuY29tL3JlcG9zaXRvcnkwLgYIKwYBBQUHAQMEIjAgMAoGCCsGAQUFBwsCMAgGBgQAjkYBATAIBgYEAI5GAQQw" +
      "DgYDVR0PAQH/BAQDAgbAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMDgGA1UdEgQxMC+kLTArMSkwJwYDVQQKEyBaZXJ0RVMgUmVjb2duaXRp" +
      "b24gQm9keTogS1BNRyBBRzAfBgNVHSMEGDAWgBSLS23t0ym5BhnsOTmp8JeEasvv3zA4BgNVHR8EMTAvMC2gK6AphidodHRwOi8vY3JsLnF1" +
      "b3ZhZGlzZ2xvYmFsLmNvbS9xdnJjYS5jcmwwHQYDVR0OBBYEFKbXP8sJeOWM8yiBjD3lz5XNrW9AMA0GCSqGSIb3DQEBCwUAA4IBAQBJcm6H" +
      "6CIxXc9hczAIQ6EJEHWLokhiVPj97Dar6Lm5hBATxkZOxZ+n/F8s3ccDt7Tv6qBB/1x5LlTz2leR/4YUxOTx1CIOwbeX6/aV3cMmKbpFqNaM" +
      "8L29obWm6nm51kS1yyvQaJAAmVlAXRoj4TOlq/SLkUZU4n7mDB5oaZLgCRr45ZpsGiGnmPfLg2nMIXu9eUwQm/Xffp0+wRWXvZMc7UhLtJsr" +
      "HFuHzFW2w8yLRzyC1RB8+syf9f5cweArBjuyVjdeCe3o0E9dUVSBgp4Ulu3x9hLJ9ps1+xt/HtM2VYEDiIlF5CLzyhm/0Egdss8o+TJRSQWq" +
      "43roK5RW7Gle";

  public final static String SIGNING_CERTIFICATE = "MIIFEzCCA/ugAwIBAgIQSXxaK/qTYahTT77Z9I56EjANBgkqhkiG9w0BAQUFADB" +
      "sMQswCQYDVQQGE" +
      "wJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1czEfMB0GA1UEAwwWVEVTVCBvZiBFU1RFSUQtU0sgMjAxMTEYMBYGCSqGS" +
      "Ib3DQEJARYJcGtpQHNrLmVlMB4XDTE0MDQxNzExNDUyOVoXDTE2MDQxMjIwNTk1OVowgbQxCzAJBgNVBAYTAkVFMQ8wDQYDVQQKDAZFU1RFS" +
      "UQxGjAYBgNVBAsMEWRpZ2l0YWwgc2lnbmF0dXJlMTEwLwYDVQQDDCjFvcOVUklOw5xXxaBLWSxNw4RSw5wtTMOWw5ZaLDExNDA0MTc2ODY1M" +
      "RcwFQYDVQQEDA7FvcOVUklOw5xXxaBLWTEWMBQGA1UEKgwNTcOEUsOcLUzDlsOWWjEUMBIGA1UEBRMLMTE0MDQxNzY4NjUwggEiMA0GCSqGS" +
      "Ib3DQEBAQUAA4IBDwAwggEKAoIBAQChn9qVaA+x3RkDBrD5ujwfnreK5/Nb+Nvo9Vg5OLMn3JKUoUhFX6A/q5lBUylK/CU/lNRTv/kicqnu1" +
      "aCyAiW0XVYk8jrOI1wRbHeyBMq/5gVm/vbbRtMi/XGLkgMZ5UDxY0QZfmu8wlRJ8164zRNocuUJLLXWOB6vda2RRXC3Cix4TDvQwGmPrQQJ8" +
      "dzDIJEkLS7NCLBTcndm7buQegRc043gKMjUmRhGZEzF4oJa4pMfXqeSa+PUtrNyNNNQaOwTH29R8aFfGU2xorVvxoUieNipyWMEz8BTUGwwI" +
      "ceapWi77loBV/VQfStXnQNu/s6BC04ss43O6sK70MB1qlRZAgMBAAGjggFmMIIBYjAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIGQDCBmQYDV" +
      "R0gBIGRMIGOMIGLBgorBgEEAc4fAwEBMH0wWAYIKwYBBQUHAgIwTB5KAEEAaQBuAHUAbAB0ACAAdABlAHMAdABpAG0AaQBzAGUAawBzAC4AI" +
      "ABPAG4AbAB5ACAAZgBvAHIAIAB0AGUAcwB0AGkAbgBnAC4wIQYIKwYBBQUHAgEWFWh0dHA6Ly93d3cuc2suZWUvY3BzLzAdBgNVHQ4EFgQUE" +
      "jVsOkaNOGG0GlcF4icqxL0u4YcwIgYIKwYBBQUHAQMEFjAUMAgGBgQAjkYBATAIBgYEAI5GAQQwHwYDVR0jBBgwFoAUQbb+xbGxtFMTjPr6Y" +
      "tA0bW0iNAowRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL3d3dy5zay5lZS9yZXBvc2l0b3J5L2NybHMvdGVzdF9lc3RlaWQyMDExLmNybDANB" +
      "gkqhkiG9w0BAQUFAAOCAQEAYTJLbScA3+Xh/s29Qoc0cLjXW3SVkFP/U71/CCIBQ0ygmCAXiQIp/7X7JonY4aDz5uTmq742zZgq5FA3c3b4N" +
      "tRzoiJXFUWQWZOPE6Ep4Y07Lpbn04sypRKbVEN9TZwDy3elVq84BcX/7oQYliTgj5EaUvpe7MIvkK4DWwrk2ffx9GRW+qQzzjn+OLhFJbT/Q" +
      "Wi81Q2CrX34GmYGrDTC/thqr5WoPELKRg6a0v3mvOCVtfIxJx7NKK4B6PGhuTl83hGzTc+Wwbaxwjqzl/SUwCNd2R8GV8EkhYH8Kay3Ac7Qx" +
      "3agrJJ6H8j+h+nCKLjIdYImvnznKyR0N2CRc/zQ+g==";

}
